[package]
name = "vortex-common"
version = "0.2.2"
edition = "2021"
description = "Interface messages and data struct of Vortex protocol contracts"
license = "Apache-2.0"
readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
cosmwasm-std = { version = "1.0.0-beta5" }
cosmwasm-storage = { version = "1.0.0-beta5" }
cw-storage-plus = "0.13.2"
cw2 = "0.13.2"
cw20 = "0.13.2"
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde-json-wasm = "0.4.1"
thiserror = { version = "1.0.26" }
base64 = { version = "0.13.0" }
semver = "1"

[dependencies.forward_ref]
version = "1"

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta5" }
